# Generated by Django 3.2.7 on 2022-02-06 19:42

import wall_e_models.customFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0003_auto_20220204_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=37)),
                ('user_id', models.BigIntegerField()),
                ('mod', models.CharField(max_length=37, null=True)),
                ('mod_id', models.BigIntegerField(null=True)),
                ('ban_date', models.BigIntegerField(null=True)),
                ('reason', models.CharField(max_length=512)),
                ('unban_date', models.BigIntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'wall_e_models_ban_records',
            },
        )
    ]
