# Generated by Django 3.2.20 on 2023-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0010_embedavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banrecord',
            name='unban_date',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='banrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'unban_date'), name='unique_active_ban'),
        ),
    ]
