# Generated by Django 3.2.20 on 2025-01-19 21:35

from django.db import migrations
import wall_e_models.customFields


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0025_userpoint_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='last_updated_date',
            field=wall_e_models.customFields.PSTDateTimeField(default=None, null=True),
        ),
    ]
