# Generated by Django 4.2.17 on 2025-01-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0026_userpoint_last_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banrecord',
            name='is_purged',
        ),
        migrations.RemoveField(
            model_name='banrecord',
            name='purge_window_days',
        ),
    ]
