# Generated by Django 3.2.20 on 2025-03-02 08:24

from django.db import migrations
import wall_e_models.customFields


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0027_userpoint_being_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='discord_avatar_link_expiry_date',
            field=wall_e_models.customFields.PSTDateTimeField(default=wall_e_models.customFields.pstdatetime.now, null=True),
        ),
    ]
