# Generated by Django 3.2.20 on 2025-04-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0028_alter_userpoint_discord_avatar_link_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='outsized_profile_pic',
            field=models.BooleanField(default=False),
        ),
    ]
