# Generated by Django 4.2.17 on 2025-04-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0029_userpoint_outsized_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banrecord',
            name='is_purged',
        ),
        migrations.RemoveField(
            model_name='banrecord',
            name='purge_window_days',
        ),
    ]
