# Generated by Django 4.2.17 on 2025-07-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0030_remove_banrecord_is_purged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactRole',
            fields=[
                ('react_role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(unique=True)),
                ('emoji_roles_json', models.TextField()),
            ],
            options={
                'db_table': 'wall_e_models_react_roles',
            },
        ),
    ]
