# Generated by Django 3.2.20 on 2025-07-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0030_remove_banrecord_is_purged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='concurrent_attempts',
            field=models.BigIntegerField(default=0),
        ),
    ]
