# Generated by Django 4.2.22 on 2025-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_e_models', '0031_userpoint_concurrent_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactRole',
            fields=[
                ('react_role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(unique=True)),
                ('emoji_roles_json', models.TextField()),
            ],
            options={
                'db_table': 'wall_e_models_react_roles',
            },
        ),
    ]
